export const paths = {
  dashboard: '/',
  orders: '/orders',
  inventory: '/inventory',
  inventoryProducts: '/inventory/products',
  inventoryProductNew: '/inventory/products/new',
  recipes: '/recipes',
  recipeNew: '/recipes/new',
  recipeEdit: (recipeId: string) => `/recipes/${recipeId}/edit`,
  purchases: '/purchases',
  billing: '/billing',
  billingInvoiceNew: "/billing/invoices/new",
  billingInvoicePreview: (invoiceId: string) =>`/billing/invoices/${invoiceId}`,
  administration: '/administration',
  administrationUsers: '/administration/users',
  administrationUserNew: '/administration/users/new',
  administrationBusiness: '/administration/settings/business',
  administrationBranches: '/administration/settings/branches',
  login: '/login',
} as const;
