export const paths = {
  dashboard: '/',
  orders: '/orders',
  inventory: '/inventory',
  inventoryProducts: '/inventory/products',
  inventoryProductNew: '/inventory/products/new',
  recipes: '/recipes',
  purchases: '/purchases',
  billing: '/billing',
  administration: '/administration',
  administrationUsers: '/administration/users',
  administrationUserNew: '/administration/users/new',
  administrationBusiness: '/administration/settings/business',
  administrationBranches: '/administration/settings/branches',
  login: '/login',
} as const;
